-- CREA UNA BASE DE DATOS PLUGGABLE (PDB) LLAMADA "BIBLIOTECA"
CREATE PLUGGABLE DATABASE biblioteca  
ADMIN USER admin IDENTIFIED BY admin_password  
FILE_NAME_CONVERT = ('opt/oracle/oradata/FREE/pdbseed/', 'opt/oracle/oradata/FREE/pdb_biblioteca/');

-- MUESTRA EL NOMBRE DE LA BASE DE DATOS ACTUAL
SHOW CON_NAME;

-- CAMBIA AL CONTEXTO DE LA BASE DE DATOS PLUGGABLE "BIBLIOTECA"
ALTER SESSION SET CONTAINER = biblioteca;

-- MUESTRA LAS BASES DE DATOS PLUGGABLES DISPONIBLES
SHOW PDBS;

-- ABRE LA BASE DE DATOS PLUGGABLE "BIBLIOTECA" PARA SU USO
ALTER PLUGGABLE DATABASE biblioteca OPEN;

-- CREA UN USUARIO LLAMADO "BIBLIOTECA_ADMIN_MSV" CON CONTRASEÑA "Biblioteca1234"
CREATE USER biblioteca_admin_msv IDENTIFIED BY Biblioteca1234;

-- CONCEDE PRIVILEGIOS DE CONEXIÓN Y RECURSOS AL USUARIO
GRANT CONNECT, RESOURCE TO biblioteca_admin_msv;

-- OTORGA PERMISO PARA USAR ESPACIO ILIMITADO EN TABLESPACES
GRANT UNLIMITED TABLESPACE TO biblioteca_admin_msv;

-- ASIGNA PRIVILEGIOS PARA CREAR SESIONES, TABLAS, VISTAS, PROCEDIMIENTOS, SECUENCIAS Y TRIGGERS
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO biblioteca_admin_msv;
